set(GTEST_ROOT "${CMAKE_SOURCE_DIR}/third_party/gtest")
if(NOT TARGET GTest::gtest)
    set(gtest_force_shared_crt ON CACHE BOOL "" FORCE)
    add_subdirectory(${GTEST_ROOT} build-gtest EXCLUDE_FROM_ALL)
endif()

add_subdirectory(sycl_device_detect)
add_subdirectory(merge_segments)
add_subdirectory(bench_vad)
add_subdirectory(config_ui)
enable_testing()
